### ISSUE TITLE
Group based on item ratings or rankings

### ISSUE THREAD

**Issue by simonayzman** [tdimiduk/groupeng#6]
I'm trying to group students into teams based on how important something is to them. For instance, there will be some topics like **poverty**, **elections**, **environment**, etc.

I have two options. First, students can rate each item **1** to **5** (**not important at all** to **very important**). Second, students can rank items among themselves (**environment** is first, **poverty** is second, etc.).

For both option 1 and option 2, what woud be the best way to group people in teams so that they can work with similarly minded people? How should the configuration and spreadsheet look? Thank you!

**Comment by vivarose** [comment]
You could **aggregate** the students by their top choice.

See this example where they aggregate by project choice: 
https://groupeng.org/files/GroupEng_Instructions.pdf
